platform: linux
image_resource:
  type: docker-image
  source: {repository: golang, tag: 1.7-alpine }

run:
  path: ./container/build.sh
  
inputs:
  - name: container
  - name: src
    path: gopath/src/github.com/skynetservices/skydns

outputs:
  - name: out
