---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.6-alpine

inputs:
  - name: skydns-container-src
  - name: skydns-git
    path: gopath/src/github.com/skynetservices/skydns

outputs:
  - name: skydns-build
  
run:
  path: ./skydns-container-src/build.sh
